workflows:
  version: 2.1
  deploy-to-heroku:
    jobs:
      - build
      - wait-for-approval:
          type: approval
          requires:
            - build
      - heroku/deploy-via-git:
          name: development-deployment
          app-name: enso-street
          requires:
            - wait-for-approval
      - wait-for-production-approval:
          type: approval
          requires:
            - development-deployment
      - heroku/deploy-via-git:
          name: production-deployment
          app-name: enso-street-web-ui-prod
          requires:
            - wait-for-production-approval

version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  build:
    working_directory: ~/enso-street
    docker:
      - image: circleci/node:8-browsers

    steps:
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: unit tests
          command: |
            npm test

      - run:
          name: browser tests
          command: |
            nohup bash -c 'npm run startHttpDev' &
            sleep 5
            ./node_modules/nightwatch/bin/nightwatch
