workflows:
  version: 2.1
  deploy-to-heroku:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build

version: 2.1
orbs:
  heroku: circleci/heroku@0.0.8

jobs:
  build:
    working_directory: ~/enso-street
    docker:
      - image: circleci/node:8-browsers

    steps:
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: build deployable
          command: |
            npm rebuild node-sass
            npm run build

      - run:
          name: tests
          command: |
            npm test